# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15b6debd7b92e48f6678a50a65948ca2a5a84e849900d86d79381ecbbd739662b5b3987f71f29c14720df2c3356b1ce39fb48e2429fc40b58690f83f8cd3e907

test:
  secret_key_base: 810b865659206f4c6c03a7d59cf378b153eee069e47dbfbcee0ced28bb7d101d248070bb4b533ae07aaf0878f687953c7a43ac4ba4262df2b7c55292ae2d07d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
